### ISSUE TITLE
Camera rattles/shakes when turning or moving

### ISSUE THREAD

**Issue by Vine2D** [aarroz/simplefps#1]
As stated in the title, the camera rattles, shakes and vibrates while either rotating the camera or walking with the Player instance. This behavior stops if the Player instance stops moving and the camera stops rotating.

**Comment by aarroz** [comment]
This is a bug with the Bullet physics implementation in Godot. https://github.com/godotengine/godot/issues/15834
Setting physics to GodotPhysics will make it smoother.

**Comment by alex9099** [comment]
isn't there any workarround that can be made? 
GodotPhysics seem to have input lag

**Comment by aarroz** [comment]
The issue on the Godot repository has a workaround available. It's not a fix that I hoped was necessary, but you can try it if you want to use the Bullet back-end. Let me know how it works.

**Comment by alex9099** [comment]
GodotPhysics seem to work fine if _process gets changed by _physics_process

Maybe GodotPhysics will not process if there is some input detected, not sure

**Comment by alex9099** [comment]
Since godotPhysics is going to be deprecated this must be corrected :)

**Comment by aarroz** [comment]
Corrected. Now uses KinematicBody. Translate is still used for movement, but using move_and_collide for simulated gravity seems to work for collisions. However, this is a hack to make it work so there's ways to improve it.
