### ISSUE TITLE
Why use RigidBody instead of KinematicBody?

### ISSUE THREAD

**Issue by alex9099** [aarroz/simplefps#2]
Hi,
Well, what the title asks, is rigidbody easier to code (or makes a smaller code?)?

**Comment by aarroz** [comment]
RigidBody was easier to code. When I tried KinematicBody, movement was relative to the world and not the body. So, moving the body forward would not update when the body rotated.

**Comment by aarroz** [comment]
Switched to KinematicBody for better movement. Found a way to make it work.
