### ISSUE TITLE
Feature Request: Sprinting

### ISSUE THREAD

**Issue by BracerJack** [aarroz/simplefps#4]
I LOVE this, drag and drop and it just works, not even a need to configure the input map, Thank you !!!
I literally just drag and drop this in my project to get fps abilities, so convenient, perfect, and it allows me to just focus on everything else.

May I request for a shift key to speed up the walking ? That would just complete the package in my personal opinion.

**Comment by aarroz** [comment]
> May I request for a shift key to speed up the walking ? That would just complete the package in my personal opinion.

I'll look into adding this!

**Comment by aarroz** [comment]
[Added](https://github.com/aarroz/simplefps/commit/83ceef7c3b5ace991b2a8f5d8438063b09e3b031) a barebones sprinting (you can sprint backwards with it). I'll fix it later as I wanted to get this released before LGJ 2023.
